name: Deploy JS Bundles

push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - run: npm run build
      - name: Create latest bundle files
        run: cp ./lib/bundle*.js ./demo/out/.
      - name: Create tagged bundle files
        run: mkdir ./demo/out/${GITHUB_REF##*/} && cp ./lib/bundle*.js ./demo/out/${GITHUB_REF##*/}/.
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: demo/out
